In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\saqla\Desktop\Python Certification for Data Science\In Class Practice Codes\11. Module 11\m11_toupload\Recommend.csv',names=['user_id', 'movie_id', 'rating', 'timestamp'])
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [3]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0] 
n_movies = df.movie_id.unique().shape[0]
train_data, test_data = train_test_split(df, test_size=0.25)

In [21]:
n_users

943

In [20]:
axis = np.newaxis
axis

In [8]:
train_data_matrix = np.zeros((n_users, n_movies))
for line in train_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    train_data_matrix[line[1]-1, line[2]-1] = line[3] 
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [9]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:, np.newaxis] 
ratings_diff = (train_data_matrix - mean_user_rating) 
user_pred = mean_user_rating + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.56903555e+00,  5.70878588e-01,  4.87094038e-01, ...,
         2.90671269e-01,  2.93191102e-01,  2.93082059e-01],
       [ 1.32637426e+00,  2.88418774e-01,  1.67174470e-01, ...,
        -6.00582619e-02, -5.67994139e-02, -5.67568491e-02],
       [ 1.31183515e+00,  2.40763508e-01,  1.27681108e-01, ...,
        -1.04315487e-01, -1.01072647e-01, -1.00962502e-01],
       ...,
       [ 1.17934131e+00,  2.01500239e-01,  8.48088486e-02, ...,
        -1.35187431e-01, -1.32133325e-01, -1.32039526e-01],
       [ 1.35710544e+00,  3.19535832e-01,  2.26611185e-01, ...,
         1.32605284e-03,  4.04065580e-03,  4.40619450e-03],
       [ 1.39436011e+00,  3.71016891e-01,  3.00601803e-01, ...,
         9.98682553e-02,  1.02322773e-01,  1.02478513e-01]])

In [11]:
user_similarity

array([[0.        , 0.91216145, 0.95378559, ..., 0.89988708, 0.87155843,
        0.71726828],
       [0.91216145, 0.        , 0.89871025, ..., 0.88372604, 0.85340237,
        0.94180009],
       [0.95378559, 0.89871025, 0.        , ..., 1.        , 0.89540442,
        0.96418477],
       ...,
       [0.89988708, 0.88372604, 1.        , ..., 0.        , 0.92263042,
        0.95529372],
       [0.87155843, 0.85340237, 0.89540442, ..., 0.92263042, 0.        ,
        0.84997956],
       [0.71726828, 0.94180009, 0.96418477, ..., 0.95529372, 0.84997956,
        0.        ]])

In [12]:
movie_similarity

array([[0.        , 0.71680191, 0.74553302, ..., 1.        , 0.94529779,
        0.94529779],
       [0.71680191, 0.        , 0.81899962, ..., 1.        , 0.90983304,
        1.        ],
       [0.74553302, 0.81899962, 0.        , ..., 1.        , 1.        ,
        0.89181723],
       ...,
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [0.94529779, 0.90983304, 1.        , ..., 1.        , 0.        ,
        1.        ],
       [0.94529779, 1.        , 0.89181723, ..., 1.        , 1.        ,
        0.        ]])

In [13]:
mean_user_rating 

array([[0.44233056],
       [0.10939358],
       [0.06539834],
       [0.039239  ],
       [0.2175981 ],
       [0.3608799 ],
       [0.70332937],
       [0.09453032],
       [0.05053508],
       [0.33709869],
       [0.27407848],
       [0.09690844],
       [0.88168847],
       [0.17241379],
       [0.12722949],
       [0.28894174],
       [0.04399524],
       [0.45838288],
       [0.02734839],
       [0.07431629],
       [0.21997622],
       [0.19678954],
       [0.26040428],
       [0.14684899],
       [0.15219976],
       [0.13436385],
       [0.02972652],
       [0.13436385],
       [0.05112961],
       [0.07193817],
       [0.05529132],
       [0.06302021],
       [0.03804994],
       [0.03686088],
       [0.03626635],
       [0.02913199],
       [0.09750297],
       [0.21997622],
       [0.03210464],
       [0.04399524],
       [0.10047562],
       [0.29904875],
       [0.36206897],
       [0.23959572],
       [0.06599287],
       [0.05945303],
       [0.02853746],
       [0.129

In [14]:
ratings_diff

array([[ 4.55766944,  2.55766944,  3.55766944, ..., -0.44233056,
        -0.44233056, -0.44233056],
       [-0.10939358, -0.10939358, -0.10939358, ..., -0.10939358,
        -0.10939358, -0.10939358],
       [-0.06539834, -0.06539834, -0.06539834, ..., -0.06539834,
        -0.06539834, -0.06539834],
       ...,
       [ 4.96789536, -0.03210464, -0.03210464, ..., -0.03210464,
        -0.03210464, -0.03210464],
       [-0.16171225, -0.16171225, -0.16171225, ..., -0.16171225,
        -0.16171225, -0.16171225],
       [-0.25267539,  4.74732461, -0.25267539, ..., -0.25267539,
        -0.25267539, -0.25267539]])

In [15]:
mean_user_rating + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T

array([[ 1.56903555e+00,  5.70878588e-01,  4.87094038e-01, ...,
         2.90671269e-01,  2.93191102e-01,  2.93082059e-01],
       [ 1.32637426e+00,  2.88418774e-01,  1.67174470e-01, ...,
        -6.00582619e-02, -5.67994139e-02, -5.67568491e-02],
       [ 1.31183515e+00,  2.40763508e-01,  1.27681108e-01, ...,
        -1.04315487e-01, -1.01072647e-01, -1.00962502e-01],
       ...,
       [ 1.17934131e+00,  2.01500239e-01,  8.48088486e-02, ...,
        -1.35187431e-01, -1.32133325e-01, -1.32039526e-01],
       [ 1.35710544e+00,  3.19535832e-01,  2.26611185e-01, ...,
         1.32605284e-03,  4.04065580e-03,  4.40619450e-03],
       [ 1.39436011e+00,  3.71016891e-01,  3.00601803e-01, ...,
         9.98682553e-02,  1.02322773e-01,  1.02478513e-01]])

In [16]:
movie_pred = train_data_matrix.dot(movie_similarity) / np.array([np.abs(movie_similarity).sum(axis=1)])
movie_pred

array([[0.36825511, 0.38260323, 0.39345261, ..., 0.44259369, 0.43635777,
        0.43272601],
       [0.09516271, 0.10711422, 0.10344075, ..., 0.10945866, 0.10926448,
        0.10910169],
       [0.06273553, 0.06616197, 0.06392486, ..., 0.06543724, 0.06528241,
        0.06599816],
       ...,
       [0.02308426, 0.02945989, 0.02780436, ..., 0.03212374, 0.0315281 ,
        0.03165721],
       [0.13753618, 0.14804693, 0.15525881, ..., 0.16180845, 0.15895721,
        0.16113824],
       [0.20598011, 0.19885096, 0.22124218, ..., 0.2528257 , 0.24675961,
        0.24729156]])

In [17]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def rmse(pred, test):
    pred = pred[test.nonzero()].flatten() 
    test = test[test.nonzero()].flatten()
    return sqrt(mean_squared_error(pred, test))

In [18]:
rmse(user_pred, test_data_matrix)

3.122768938624934

In [19]:
rmse(movie_pred, test_data_matrix)

3.450078380089116

### There is a module called Turicreate to do all these tasks